version: '2.19.1'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - mysql-db

  
  mysql-db:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - .env
