name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the workflow on an Ubuntu machine (GitHub's default runner)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This action checks out your repo so the workflow can access the latest code

    - name: Check SSH Agent
      run: |
        echo "Checking SSH agent..."
        ssh-add -l  # List keys currently in the SSH agent

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3  # This action sets up the SSH agent to authenticate to your EC2 instance
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Fetches your private SSH key from GitHub secrets

    - name: Cache Node.js dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm  # Cache the npm cache directory
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  # Cache key is based on the package-lock.json hash
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm install  # Installs all dependencies in your repo

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@<${{ secrets.EC2_PUBLIC_IP }}> << 'EOF'
          cd ~/audiophile-node-api  # Navigate to your app directory on the EC2 instance
          git pull origin main  # Pull the latest changes from GitHub (main branch)
          npm install  # Install any new dependencies that were added
          pm2 restart audiophile-api  # Restart the PM2 process to apply updates
        EOF
